config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  root 'home#index'
  get 'home/about'
  get 'home/lookup'
  post '/home/lookup' => 'home/lookup'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cryptos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update, :destroy, :show]
  # GET /cryptos or /cryptos.json
  def index
    @cryptos = Crypto.all
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=89c05170-722e-4b74-85e7-012df26e1894&start=1&limit=5000&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_crypto = JSON.parse(@response)
    @profit_loss = 0
  end

  # GET /cryptos/1 or /cryptos/1.json
  def show
    @cryptos = Crypto.all
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=89c05170-722e-4b74-85e7-012df26e1894&start=1&limit=5000&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @show_crypto = JSON.parse(@response)
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
  end

  # POST /cryptos or /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: "Crypto was successfully created." }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1 or /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: "Crypto was successfully updated." }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1 or /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: "Crypto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end

    def correct_user
      @correct = current_user.cryptos.find_by(id: params[:id])
      redirect_to cryptos_path, notice: "Not Authorized to edit this entry" if @correct.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=89c05170-722e-4b74-85e7-012df26e1894&start=1&limit=5000&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @coins = JSON.parse(@response)
    @my_coins = ["BTC", "ETH", "ADA", "BNB", "SOL", "XRP", "DOT", "LINK", "ALGO", "AVAX", "LTC", "ATOM", "MATIC", "XLM", "VET", "XMR", "THETA", "AAVE", "USDT", "BCH", "DOGE", "FIL", "TRX", "XTZ", "ETC"]
  end

  def about

  end

  def lookup
    @url = 'https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=89c05170-722e-4b74-85e7-012df26e1894&start=1&limit=5000&convert=USD'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @lookup_coin = JSON.parse(@response)


    @symbol = params[:symbol]

    if @symbol
      @symbol = @symbol.upcase
    end

    if @symbol == ""
      @symbol = "You did not enter a currency!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto) do |form| %>
  <% if crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
        <% crypto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :symbol %>
    <%= form.text_field :symbol %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, value: current_user.id, type:"hidden" %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned %>
  </div>

  <button type="button" class="btn btn-light">
    <%= form.submit %>
  </button>

<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing Crypto</h1>

<%= render 'form', crypto: @crypto %>
<br>
<%= link_to 'Show', @crypto, class: "btn btn-outline-secondary" %> |
<%= link_to 'Back', cryptos_path, class: "btn btn-outline-secondary" %>

app/views/cryptos/index.html.erb
<br>
<h1>My Cryptocurrency Portfolio</h1>
<br>
<table class="table table-info table-hover table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Symbol</th>
      <th>Current Price</th>
      <th>24 Hour Change</th>
      <th>Amount Owned</th>
      <th>Dollar Cost Average</th>
      <th>Total Invested</th>
      <th>Current Value</th>
      <th>Profit/Loss</th>
    </tr>
  </thead>

  <tbody>
    <% @cryptos.each do |crypto| %>
      <% if crypto.user_id == current_user.id %>
        <% if crypto.symbol %>
          <% crypto.symbol = crypto.symbol.upcase %>
        <% end %>
        <tr>
        <% for x in @lookup_crypto['data'] %>
            <% if crypto.symbol == x['symbol'] %>
              <td><%= link_to x['name'], crypto %> </td>
              <td><%= crypto.symbol %></td>
              <td>$<%= x['quote']['USD']['price'] %></td>
              <td><%= x['quote']['USD']['percent_change_24h'] %>%</td>
              <td><%= crypto.amount_owned %></td>
              <td><%= number_to_currency(crypto.cost_per) %></td>
              <td><%= number_to_currency(crypto.cost_per * crypto.amount_owned) %></td>
              <td> <%= number_to_currency(x['quote']['USD']['price'].to_d * crypto.amount_owned) %> </td>
              <td><%= number_to_currency((x['quote']['USD']['price'].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned))%></td>
              <% @profit_loss += (x['quote']['USD']['price'].to_d * crypto.amount_owned) - (crypto.cost_per * crypto.amount_owned)%>
            <% end %>
        <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<br/>
<strong>Portfolio Profit/Loss: </strong><%= number_to_currency(@profit_loss)%>
<br>
<br>
<%= link_to 'New Crypto', new_crypto_path, class: "btn btn-outline-success" %>

app/views/cryptos/new.html.erb
<br><h1>New Crypto</h1><br>
<p>Enter the relevant information about your latest cryptocurrency purchase.</p>
<br>
<%= render 'form', crypto: @crypto %>
<br>
<%= link_to 'Back', cryptos_path, class: "btn btn-outline-secondary" %>

app/views/cryptos/show.html.erb
<br/>
<br/>
<h2>Selected Purchase</h2>
<br/>
<div class="card text-dark bg-info mb-3" style="max-width: 20rem;">
  <div class="card-body">
    <h5 class="card-title">
      <strong>Symbol:</strong>
      <%= @crypto.symbol.upcase %>
    </h5>

    <h6 class="card-title">
      <strong>Cost per:</strong>
      <%= number_to_currency(@crypto.cost_per) %>
    </h6>

    <h6 class="card-title">
      <strong>Amount owned:</strong>
      <%= @crypto.amount_owned %>
    </h6>
  </div>
</div>
<br><br>

<%= link_to 'Edit', edit_crypto_path(@crypto), class: "btn btn-outline-success" %> |
<%= link_to 'Delete', crypto_path(@crypto), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %> |
<%= link_to 'Back', cryptos_path, class: "btn btn-outline-primary" %>

app/views/home/_flash.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissible">
        <button class="close" data-dismiss="alert">
            <i class="glyphicon glyphicon-remove-circle"></i>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Home", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
       <li class="nav-item">
            <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Search", home_lookup_path, class:"nav-link" %>
        </li>
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Add Purchase", new_crypto_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "My Portfolio", cryptos_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Log In", new_user_session_path, class:"nav-link" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<br>
<h1>About Us</h1>
<br><br />
<h3>Get started Managing, Storing, and Tracking your cryptocurrency portfolio with us today!</h3>

app/views/home/index.html.erb
<h1>Welcome to My Cryptocurrency Portfolio app!</h1>
<br><br/>

<% if user_signed_in? %>
    <h3>Popular Cryptocurrencies</h3>
<% else %>
    <h3>Please Sign up or Log in to get started.</h3>
<% end %>

<br/><br/>

<% @coins %>
<ol class="list-group list-group-numbered ">
<% for x in @coins['data'] %>
 <% for coin in @my_coins %>
     <% if coin == x['symbol'] %>
         <li class="list-group-item list-group-item-info"><%= x['name'] %>: $<%= x['quote']['USD']['price'] %></li><br /><br />
     <% end %>
 <% end %>
<% end %>
</ol>

app/views/home/lookup.html.erb
<br />
<h3>Look up a Cryptocurrency!</h3>
<br />
<br />

<%= form_tag home_lookup_path, :method => 'POST' do %>
    <%= text_field_tag 'symbol', nil, placeholder: "Enter Crypto Symbol", size: 50 %>
    <%= submit_tag 'Lookup Quote' %>
<% end%>

<% if @symbol%>
    <% for x in @lookup_coin['data'] %>
        <% if @symbol == x['symbol'] %>
            <li class="list-group-item list-group-item-info"><%= x['name'] %>: $<%= x['quote']['USD']['price'] %></li><br /><br />
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">


    <title>My Cryptocurrency Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= render 'home/flash' %>
      <%= yield %>
    </div>
  </body>
</html>